### ISSUE TITLE
[Bug 🐞]: Patch declairs a pass FOR KerbalismDefault, should be NEEDS

### ISSUE THREAD

**Issue by Rodg88** [zer0Kerbal/MiniSampleReturnCapsule#103]
### Brief description of your issue (aka the problem)

This patch has some errors in it's syntax : `MiniSampleReturnCapsule/Compatibility/Kerbalism/@part[msrc-parachute]:NEEDS[MiniSampleReturnCapsule]:FOR[KerbalismDefault]:FOR[MiniSampleReturnCapsule]`

this causes other mod's kerbalism patches to activate when kerbalism isn't installed. Just need to change it to `:NEEDS[KerbalismDefault]:FOR[MiniSampleReturnCapsule]`

### KSP version

1.12.5

### Version of addon
unknown

### Steps to reproduce the behavior or issue

Install MSRC without Kerbalism, and the log will show a KERBALISMDEFAULT pass active.

### Environment

```shell
https://drive.google.com/drive/folders/1uhEW2Z6MJ0jGaEIyDTLNiWQzxq6Pesnn
```

### Log files

dee drive link

### How did you download and install this?

SpaceDock (manual install)

**Comment by Rodg88** [comment]
But looking at the current version of the mod, it looks like it's already fixed, and the user might just have an old version

**Comment by Rodg88** [comment]
Yep it was an old version

**Comment by zer0Kerbal** [comment]
> But looking at the current version of the mod, it looks like it's already fixed, and the user might just have an old version

> Yep it was an old version

Thank you @Rodg88 !
