### ISSUE TITLE
[BUG] Kerbalism config

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/MiniSampleReturnCapsule#90]
[Rodger](https://forum.kerbalspaceprogram.com/index.php?/profile/153575-rodger/)

[Posted 40 minutes ago](https://forum.kerbalspaceprogram.com/index.php?/topic/204186-1123-mini-sample-return-capsule-msrc-v1422/&do=findComment&comment=4279184)
Come across an issue where this mod is using FOR[KerbalismDefault] instead of NEEDS[KerbalismDefault], so it's declaring the pass that other patches are looking for to enable kerbalism compat. FOR should only really be used by the mod itself.

Should be a simple fix, I think it's only in Compatibility/Kerbalism.cfg

![image](https://user-images.githubusercontent.com/39887717/235788196-451a14c0-4461-4a19-9ef0-eb3d04d3cbf8.png)

**Comment by zer0Kerbal** [comment]
https://github.com/zer0Kerbal/MiniSampleReturnCapsule/blob/990bc45e32d4d5feec15f1847343d6d5dffb0c47/GameData/MiniSampleReturnCapsule/Compatibility/Kerbalism.cfg

**Comment by Rodg88** [comment]
This is my github account, thanks
